### ISSUE TITLE
Service dependency feature 

### ISSUE THREAD

**Issue by aadi4u** [ageric/nagios#3]
Hello Andreas,

Just wanted to check if the Service dependency feature with 4.0 will have an option to set execution dependency as well, along with the default notification dependency.

Thanks
Ashish

**Comment by ageric** [comment]
On 01/04/2013 08:38 PM, aadi4u wrote:

> Hello Andreas,
> 
> Just wanted to check if the Service dependency feature with 4.0 will
> have an option to set execution dependency as well, along with the
> default notification dependency.

If you're talking about the service parents, then no, they will work
as notification dependencies only.

/Andreas

**Comment by aadi4u** [comment]
Thanks for your response Andreas. 

We have services like JMX4Perl and NRPE_NT etc where we use proxy agents/servers to run commands. it will be useful to set all these service monitors on the monitor which checks proxy. if Proxy is unavailable, there is no reason to run all these monitors.
I see that it will be a useful optional feature to be able to set execution dependency in such cases. If you agree, will it be something you could include in coming version of 4.0

Thanks again for doing wonderful work.
-Ashish

**Comment by ageric** [comment]
On 01/07/2013 06:57 PM, aadi4u wrote:

> Thanks for your response Andreas.
> 
> We have services like JMX4Perl and NRPE_NT etc where we use proxy
> agents/servers to run commands. it will be useful to set all these
> service monitors on the monitor which checks proxy. if Proxy is
> unavailable, there is no reason to run all these monitors. I see that
> it will be a useful optional feature to be able to set execution
> dependency in such cases. If you agree, will it be something you
> could include in coming version of 4.0

Execution dependencies are already implemented. The parents is just to
make sure you don't get notified unnecessarily.

/Andreas
